window.pokemonFamilies = {
  // --- Kanto ---
  bulbasaur: ["bulbasaur", "ivysaur", "venusaur"],
  ivysaur: ["bulbasaur", "ivysaur", "venusaur"],
  venusaur: ["bulbasaur", "ivysaur", "venusaur"],
  charmander: ["charmander", "charmeleon", "charizard"],
  charmeleon: ["charmander", "charmeleon", "charizard"],
  charizard: ["charmander", "charmeleon", "charizard"],
  squirtle: ["squirtle", "wartortle", "blastoise"],
  wartortle: ["squirtle", "wartortle", "blastoise"],
  blastoise: ["squirtle", "wartortle", "blastoise"],
  caterpie: ["caterpie", "metapod", "butterfree"],
  metapod: ["caterpie", "metapod", "butterfree"],
  butterfree: ["caterpie", "metapod", "butterfree"],
  weedle: ["weedle", "kakuna", "beedrill"],
  kakuna: ["weedle", "kakuna", "beedrill"],
  beedrill: ["weedle", "kakuna", "beedrill"],
  pidgey: ["pidgey", "pidgeotto", "pidgeot"],
  pidgeotto: ["pidgey", "pidgeotto", "pidgeot"],
  pidgeot: ["pidgey", "pidgeotto", "pidgeot"],
  rattata: ["rattata", "raticate"],
  raticate: ["rattata", "raticate"],
  spearow: ["spearow", "fearow"],
  fearow: ["spearow", "fearow"],
  ekans: ["ekans", "arbok"],
  arbok: ["ekans", "arbok"],
  pikachu: ["pichu", "pikachu", "raichu"],
  pichu: ["pichu", "pikachu", "raichu"],
  raichu: ["pichu", "pikachu", "raichu"],
  sandshrew: ["sandshrew", "sandslash"],
  sandslash: ["sandshrew", "sandslash"],
  "nidoran♀": ["nidoran♀", "nidorina", "nidoqueen", "nidoran♂", "nidorino", "nidoking"],
  nidorina: ["nidoran♀", "nidorina", "nidoqueen", "nidoran♂", "nidorino", "nidoking"],
  nidoqueen: ["nidoran♀", "nidorina", "nidoqueen", "nidoran♂", "nidorino", "nidoking"],
  "nidoran♂": ["nidoran♀", "nidorina", "nidoqueen", "nidoran♂", "nidorino", "nidoking"],
  nidorino: ["nidoran♀", "nidorina", "nidoqueen", "nidoran♂", "nidorino", "nidoking"],
  nidoking: ["nidoran♀", "nidorina", "nidoqueen", "nidoran♂", "nidorino", "nidoking"],
  clefairy: ["cleffa", "clefairy", "clefable"],
  clefable: ["cleffa", "clefairy", "clefable"],
  cleffa: ["cleffa", "clefairy", "clefable"],
  vulpix: ["vulpix", "ninetales"],
  ninetales: ["vulpix", "ninetales"],
  jigglypuff: ["igglybuff", "jigglypuff", "wigglytuff"],
  igglybuff: ["igglybuff", "jigglypuff", "wigglytuff"],
  wigglytuff: ["igglybuff", "jigglypuff", "wigglytuff"],
  zubat: ["zubat", "golbat", "crobat"],
  golbat: ["zubat", "golbat", "crobat"],
  crobat: ["zubat", "golbat", "crobat"],
  oddish: ["oddish", "gloom", "vileplume", "bellossom"],
  gloom: ["oddish", "gloom", "vileplume", "bellossom"],
  vileplume: ["oddish", "gloom", "vileplume", "bellossom"],
  bellossom: ["oddish", "gloom", "vileplume", "bellossom"],
  paras: ["paras", "parasect"],
  parasect: ["paras", "parasect"],
  venonat: ["venonat", "venomoth"],
  venomoth: ["venonat", "venomoth"],
  diglett: ["diglett", "dugtrio"],
  dugtrio: ["diglett", "dugtrio"],
  meowth: ["meowth", "persian"],
  persian: ["meowth", "persian"],
  psyduck: ["psyduck", "golduck"],
  golduck: ["psyduck", "golduck"],
  mankey: ["mankey", "primeape"],
  primeape: ["mankey", "primeape"],
  growlithe: ["growlithe", "arcanine"],
  arcanine: ["growlithe", "arcanine"],
  poliwag: ["poliwag", "poliwhirl", "poliwrath", "politoed"],
  poliwhirl: ["poliwag", "poliwhirl", "poliwrath", "politoed"],
  poliwrath: ["poliwag", "poliwhirl", "poliwrath", "politoed"],
  politoed: ["poliwag", "poliwhirl", "poliwrath", "politoed"],
  abra: ["abra", "kadabra", "alakazam"],
  kadabra: ["abra", "kadabra", "alakazam"],
  alakazam: ["abra", "kadabra", "alakazam"],
  machop: ["machop", "machoke", "machamp"],
  machoke: ["machop", "machoke", "machamp"],
  machamp: ["machop", "machoke", "machamp"],
  bellsprout: ["bellsprout", "weepinbell", "victreebel"],
  weepinbell: ["bellsprout", "weepinbell", "victreebel"],
  victreebel: ["bellsprout", "weepinbell", "victreebel"],
  tentacool: ["tentacool", "tentacruel"],
  tentacruel: ["tentacool", "tentacruel"],
  geodude: ["geodude", "graveler", "golem"],
  graveler: ["geodude", "graveler", "golem"],
  golem: ["geodude", "graveler", "golem"],
  ponyta: ["ponyta", "rapidash"],
  rapidash: ["ponyta", "rapidash"],
  slowpoke: ["slowpoke", "slowbro", "slowking"],
  slowbro: ["slowpoke", "slowbro", "slowking"],
  slowking: ["slowpoke", "slowbro", "slowking"],
  magnemite: ["magnemite", "magneton", "magnezone"],
  magneton: ["magnemite", "magneton", "magnezone"],
  magnezone: ["magnemite", "magneton", "magnezone"],
  "farfetch’d": ["farfetch’d"],
  doduo: ["doduo", "dodrio"],
  dodrio: ["doduo", "dodrio"],
  seel: ["seel", "dewgong"],
  dewgong: ["seel", "dewgong"],
  grimer: ["grimer", "muk"],
  muk: ["grimer", "muk"],
  shellder: ["shellder", "cloyster"],
  cloyster: ["shellder", "cloyster"],
  gastly: ["gastly", "haunter", "gengar"],
  haunter: ["gastly", "haunter", "gengar"],
  gengar: ["gastly", "haunter", "gengar"],
  onix: ["onix", "steelix"],
  steelix: ["onix", "steelix"],
  drowzee: ["drowzee", "hypno"],
  hypno: ["drowzee", "hypno"],
  krabby: ["krabby", "kingler"],
  kingler: ["krabby", "kingler"],
  voltorb: ["voltorb", "electrode"],
  electrode: ["voltorb", "electrode"],
  exeggcute: ["exeggcute", "exeggutor"],
  exeggutor: ["exeggcute", "exeggutor"],
  cubone: ["cubone", "marowak"],
  marowak: ["cubone", "marowak"],
  tyrogue: ["tyrogue", "hitmonlee", "hitmonchan", "hitmontop"],
  hitmonlee: ["tyrogue", "hitmonlee", "hitmonchan", "hitmontop"],
  hitmonchan: ["tyrogue", "hitmonlee", "hitmonchan", "hitmontop"],
  hitmontop: ["tyrogue", "hitmonlee", "hitmonchan", "hitmontop"],
  lickitung: ["lickitung", "lickilicky"],
  lickilicky: ["lickitung", "lickilicky"],
  koffing: ["koffing", "weezing"],
  weezing: ["koffing", "weezing"],
  rhyhorn: ["rhyhorn", "rhydon", "rhyperior"],
  rhydon: ["rhyhorn", "rhydon", "rhyperior"],
  rhyperior: ["rhyhorn", "rhydon", "rhyperior"],
  happiny: ["happiny", "chansey", "blissey"],
  chansey: ["happiny", "chansey", "blissey"],
  blissey: ["happiny", "chansey", "blissey"],
  tangela: ["tangela", "tangrowth"],
  tangrowth: ["tangela", "tangrowth"],
  kangaskhan: ["kangaskhan"],
  horsea: ["horsea", "seadra", "kingdra"],
  seadra: ["horsea", "seadra", "kingdra"],
  kingdra: ["horsea", "seadra", "kingdra"],
  goldeen: ["goldeen", "seaking"],
  seaking: ["goldeen", "seaking"],
  staryu: ["staryu", "starmie"],
  starmie: ["staryu", "starmie"],
  "mr. mime": ["mime jr.", "mr. mime"],
  "mime jr.": ["mime jr.", "mr. mime"],
  scyther: ["scyther", "scizor"],
  scizor: ["scyther", "scizor"],
  smoochum: ["smoochum", "jynx"],
  jynx: ["smoochum", "jynx"],
  elekid: ["elekid", "electabuzz", "electivire"],
  electabuzz: ["elekid", "electabuzz", "electivire"],
  electivire: ["elekid", "electabuzz", "electivire"],
  magby: ["magby", "magmar", "magmortar"],
  magmar: ["magby", "magmar", "magmortar"],
  magmortar: ["magby", "magmar", "magmortar"],
  pinsir: ["pinsir"],
  tauros: ["tauros"],
  magikarp: ["magikarp", "gyarados"],
  gyarados: ["magikarp", "gyarados"],
  lapras: ["lapras"],
  ditto: ["ditto"],
  eevee: ["eevee", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon"],
  vaporeon: ["eevee", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon"],
  jolteon: ["eevee", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon"],
  flareon: ["eevee", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon"],
  espeon: ["eevee", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon"],
  umbreon: ["eevee", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon"],
  leafeon: ["eevee", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon"],
  glaceon: ["eevee", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon"],
  porygon: ["porygon", "porygon2", "porygon-z"],
  porygon2: ["porygon", "porygon2", "porygon-z"],
  "porygon-z": ["porygon", "porygon2", "porygon-z"],
  omanyte: ["omanyte", "omastar"],
  omastar: ["omanyte", "omastar"],
  kabuto: ["kabuto", "kabutops"],
  kabutops: ["kabuto", "kabutops"],
  aerodactyl: ["aerodactyl"],
  munchlax: ["munchlax", "snorlax"],
  snorlax: ["munchlax", "snorlax"],
  articuno: ["articuno"],
  zapdos: ["zapdos"],
  moltres: ["moltres"],
  dratini: ["dratini", "dragonair", "dragonite"],
  dragonair: ["dratini", "dragonair", "dragonite"],
  dragonite: ["dratini", "dragonair", "dragonite"],
  mewtwo: ["mewtwo"],
  mew: ["mew"],

  // --- Johto ---
  chikorita: ["chikorita", "bayleef", "meganium"],
  bayleef: ["chikorita", "bayleef", "meganium"],
  meganium: ["chikorita", "bayleef", "meganium"],
  cyndaquil: ["cyndaquil", "quilava", "typhlosion"],
  quilava: ["cyndaquil", "quilava", "typhlosion"],
  typhlosion: ["cyndaquil", "quilava", "typhlosion"],
  totodile: ["totodile", "croconaw", "feraligatr"],
  croconaw: ["totodile", "croconaw", "feraligatr"],
  feraligatr: ["totodile", "croconaw", "feraligatr"],
  sentret: ["sentret", "furret"],
  furret: ["sentret", "furret"],
  hoothoot: ["hoothoot", "noctowl"],
  noctowl: ["hoothoot", "noctowl"],
  ledyba: ["ledyba", "ledian"],
  ledian: ["ledyba", "ledian"],
  spinarak: ["spinarak", "ariados"],
  ariados: ["spinarak", "ariados"],
  crobat: ["zubat", "golbat", "crobat"],
  chinchou: ["chinchou", "lanturn"],
  lanturn: ["chinchou", "lanturn"],
  pichu: ["pichu", "pikachu", "raichu"],
  cleffa: ["cleffa", "clefairy", "clefable"],
  igglybuff: ["igglybuff", "jigglypuff", "wigglytuff"],
  togepi: ["togepi", "togetic", "togekiss"],
  togetic: ["togepi", "togetic", "togekiss"],
  togekiss: ["togepi", "togetic", "togekiss"],
  natu: ["natu", "xatu"],
  xatu: ["natu", "xatu"],
  mareep: ["mareep", "flaaffy", "ampharos"],
  flaaffy: ["mareep", "flaaffy", "ampharos"],
  ampharos: ["mareep", "flaaffy", "ampharos"],
  bellossom: ["oddish", "gloom", "vileplume", "bellossom"],
  marill: ["azurill", "marill", "azumarill"],
  azurill: ["azurill", "marill", "azumarill"],
  azumarill: ["azurill", "marill", "azumarill"],
  sudowoodo: ["bonsly", "sudowoodo"],
  bonsly: ["bonsly", "sudowoodo"],
  hoppip: ["hoppip", "skiploom", "jumpluff"],
  skiploom: ["hoppip", "skiploom", "jumpluff"],
  jumpluff: ["hoppip", "skiploom", "jumpluff"],
  aipom: ["aipom", "ambipom"],
  ambipom: ["aipom", "ambipom"],
  sunkern: ["sunkern", "sunflora"],
  sunflora: ["sunkern", "sunflora"],
  yanma: ["yanma", "yanmega"],
  yanmega: ["yanma", "yanmega"],
  wooper: ["wooper", "quagsire"],
  quagsire: ["wooper", "quagsire"],
  espeon: ["eevee", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon"],
  umbreon: ["eevee", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon"],
  murkrow: ["murkrow", "honchkrow"],
  honchkrow: ["murkrow", "honchkrow"],
  slowking: ["slowpoke", "slowbro", "slowking"],
  misdreavus: ["misdreavus", "mismagius"],
  mismagius: ["misdreavus", "mismagius"],
  unown: ["unown"],
  wobbuffet: ["wynaut", "wobbuffet"],
  wynaut: ["wynaut", "wobbuffet"],
  girafarig: ["girafarig"],
  pineco: ["pineco", "forretress"],
  forretress: ["pineco", "forretress"],
  dunsparce: ["dunsparce"],
  gligar: ["gligar", "gliscor"],
  gliscor: ["gligar", "gliscor"],
  snubbull: ["snubbull", "granbull"],
  granbull: ["snubbull", "granbull"],
  qwilfish: ["qwilfish"],
  scizor: ["scyther", "scizor"],
  shuckle: ["shuckle"],
  heracross: ["heracross"],
  sneasel: ["sneasel", "weavile"],
  weavile: ["sneasel", "weavile"],
  teddiursa: ["teddiursa", "ursaring"],
  ursaring: ["teddiursa", "ursaring"],
  slugma: ["slugma", "magcargo"],
  magcargo: ["slugma", "magcargo"],
  swinub: ["swinub", "piloswine", "mamoswine"],
  piloswine: ["swinub", "piloswine", "mamoswine"],
  mamoswine: ["swinub", "piloswine", "mamoswine"],
  corsola: ["corsola"],
  remoraid: ["remoraid", "octillery"],
  octillery: ["remoraid", "octillery"],
  delibird: ["delibird"],
  mantine: ["mantyke", "mantine"],
  mantyke: ["mantyke", "mantine"],
  skarmory: ["skarmory"],
  houndour: ["houndour", "houndoom"],
  houndoom: ["houndour", "houndoom"],
  kingdra: ["horsea", "seadra", "kingdra"],
  phanpy: ["phanpy", "donphan"],
  donphan: ["phanpy", "donphan"],
  porygon2: ["porygon", "porygon2", "porygon-z"],
  stantler: ["stantler"],
  smeargle: ["smeargle"],
  tyrogue: ["tyrogue", "hitmonlee", "hitmonchan", "hitmontop"],
  hitmontop: ["tyrogue", "hitmonlee", "hitmonchan", "hitmontop"],
  smoochum: ["smoochum", "jynx"],
  elekid: ["elekid", "electabuzz", "electivire"],
  magby: ["magby", "magmar", "magmortar"],
  miltank: ["miltank"],
  blissey: ["happiny", "chansey", "blissey"],
  raikou: ["raikou"],
  entei: ["entei"],
  suicune: ["suicune"],
  larvitar: ["larvitar", "pupitar", "tyranitar"],
  pupitar: ["larvitar", "pupitar", "tyranitar"],
  tyranitar: ["larvitar", "pupitar", "tyranitar"],

  // --- Hoenn ---
  treecko: ["treecko", "grovyle", "sceptile"],
  grovyle: ["treecko", "grovyle", "sceptile"],
  sceptile: ["treecko", "grovyle", "sceptile"],
  torchic: ["torchic", "combusken", "blaziken"],
  combusken: ["torchic", "combusken", "blaziken"],
  blaziken: ["torchic", "combusken", "blaziken"],
  mudkip: ["mudkip", "marshtomp", "swampert"],
  marshtomp: ["mudkip", "marshtomp", "swampert"],
  swampert: ["mudkip", "marshtomp", "swampert"],
  poochyena: ["poochyena", "mightyena"],
  mightyena: ["poochyena", "mightyena"],
  zigzagoon: ["zigzagoon", "linoone"],
  linoone: ["zigzagoon", "linoone"],
  wurmple: ["wurmple", "silcoon", "beautifly", "cascoon", "dustox"],
  silcoon: ["wurmple", "silcoon", "beautifly", "cascoon", "dustox"],
  beautifly: ["wurmple", "silcoon", "beautifly", "cascoon", "dustox"],
  cascoon: ["wurmple", "silcoon", "beautifly", "cascoon", "dustox"],
  dustox: ["wurmple", "silcoon", "beautifly", "cascoon", "dustox"],
  lotad: ["lotad", "lombre", "ludicolo"],
  lombre: ["lotad", "lombre", "ludicolo"],
  ludicolo: ["lotad", "lombre", "ludicolo"],
  seedot: ["seedot", "nuzleaf", "shiftry"],
  nuzleaf: ["seedot", "nuzleaf", "shiftry"],
  shiftry: ["seedot", "nuzleaf", "shiftry"],
  taillow: ["taillow", "swellow"],
  swellow: ["taillow", "swellow"],
  wingull: ["wingull", "pelipper"],
  pelipper: ["wingull", "pelipper"],
  ralts: ["ralts", "kirlia", "gardevoir", "gallade"],
  kirlia: ["ralts", "kirlia", "gardevoir", "gallade"],
  gardevoir: ["ralts", "kirlia", "gardevoir", "gallade"],
  gallade: ["ralts", "kirlia", "gardevoir", "gallade"],
  surskit: ["surskit", "masquerain"],
  masquerain: ["surskit", "masquerain"],
  shroomish: ["shroomish", "breloom"],
  breloom: ["shroomish", "breloom"],
  slakoth: ["slakoth", "vigoroth", "slaking"],
  vigoroth: ["slakoth", "vigoroth", "slaking"],
  slaking: ["slakoth", "vigoroth", "slaking"],
  nincada: ["nincada", "ninjask", "shedinja"],
  ninjask: ["nincada", "ninjask", "shedinja"],
  shedinja: ["nincada", "ninjask", "shedinja"],
  whismur: ["whismur", "loudred", "exploud"],
  loudred: ["whismur", "loudred", "exploud"],
  exploud: ["whismur", "loudred", "exploud"],
  makuhita: ["makuhita", "hariyama"],
  hariyama: ["makuhita", "hariyama"],
  azurill: ["azurill", "marill", "azumarill"],
  nosepass: ["nosepass", "probopass"],
  skitty: ["skitty", "delcatty"],
  delcatty: ["skitty", "delcatty"],
  sableye: ["sableye"],
  mawile: ["mawile"],
  aron: ["aron", "lairon", "aggron"],
  lairon: ["aron", "lairon", "aggron"],
  aggron: ["aron", "lairon", "aggron"],
  meditite: ["meditite", "medicham"],
  medicham: ["meditite", "medicham"],
  electrike: ["electrike", "manectric"],
  manectric: ["electrike", "manectric"],
  plusle: ["plusle"],
  minun: ["minun"],
  volbeat: ["volbeat"],
  illumise: ["illumise"],
  roselia: ["budew", "roselia", "roserade"],
  budew: ["budew", "roselia", "roserade"],
  roserade: ["budew", "roselia", "roserade"],
  gulpin: ["gulpin", "swalot"],
  swalot: ["gulpin", "swalot"],
  carvanha: ["carvanha", "sharpedo"],
  sharpedo: ["carvanha", "sharpedo"],
  wailmer: ["wailmer", "wailord"],
  wailord: ["wailmer", "wailord"],
  numel: ["numel", "camerupt"],
  camerupt: ["numel", "camerupt"],
  torkoal: ["torkoal"],
  spoink: ["spoink", "grumpig"],
  grumpig: ["spoink", "grumpig"],
  spinda: ["spinda"],
  trapinch: ["trapinch", "vibrava", "flygon"],
  vibrava: ["trapinch", "vibrava", "flygon"],
  flygon: ["trapinch", "vibrava", "flygon"],
  cacnea: ["cacnea", "cacturne"],
  cacturne: ["cacnea", "cacturne"],
  swablu: ["swablu", "altaria"],
  altaria: ["swablu", "altaria"],
  zangoose: ["zangoose"],
  seviper: ["seviper"],
  lunatone: ["lunatone"],
  solrock: ["solrock"],
  barboach: ["barboach", "whiscash"],
  whiscash: ["barboach", "whiscash"],
  corphish: ["corphish", "crawdaunt"],
  crawdaunt: ["corphish", "crawdaunt"],
  baltoy: ["baltoy", "claydol"],
  claydol: ["baltoy", "claydol"],
  lileep: ["lileep", "cradily"],
  cradily: ["lileep", "cradily"],
  anorith: ["anorith", "armaldo"],
  armaldo: ["anorith", "armaldo"],
  feebas: ["feebas", "milotic"],
  milotic: ["feebas", "milotic"],
  castform: ["castform"],
  kecleon: ["kecleon"],
  shuppet: ["shuppet", "banette"],
  banette: ["shuppet", "banette"],
  duskull: ["duskull", "dusclops", "dusknoir"],
  dusclops: ["duskull", "dusclops", "dusknoir"],
  dusknoir: ["duskull", "dusclops", "dusknoir"],
  tropius: ["tropius"],
  chingling: ["chingling", "chimecho"],
  chimecho: ["chingling", "chimecho"],
  absol: ["absol"],
  wynaut: ["wynaut", "wobbuffet"],
  snorunt: ["snorunt", "glalie", "froslass"],
  glalie: ["snorunt", "glalie", "froslass"],
  froslass: ["snorunt", "glalie", "froslass"],
  spheal: ["spheal", "sealeo", "walrein"],
  sealeo: ["spheal", "sealeo", "walrein"],
  walrein: ["spheal", "sealeo", "walrein"],
  clamperl: ["clamperl", "huntail", "gorebyss"],
  huntail: ["clamperl", "huntail", "gorebyss"],
  gorebyss: ["clamperl", "huntail", "gorebyss"],
  relicanth: ["relicanth"],
  luvdisc: ["luvdisc"],
  bagon: ["bagon", "shelgon", "salamence"],
  shelgon: ["bagon", "shelgon", "salamence"],
  salamence: ["bagon", "shelgon", "salamence"],
  beldum: ["beldum", "metang", "metagross"],
  metang: ["beldum", "metang", "metagross"],
  metagross: ["beldum", "metang", "metagross"],

  // --- Sinnoh ---
  turtwig: ["turtwig", "grotle", "torterra"],
  grotle: ["turtwig", "grotle", "torterra"],
  torterra: ["turtwig", "grotle", "torterra"],
  chimchar: ["chimchar", "monferno", "infernape"],
  monferno: ["chimchar", "monferno", "infernape"],
  infernape: ["chimchar", "monferno", "infernape"],
  piplup: ["piplup", "prinplup", "empoleon"],
  prinplup: ["piplup", "prinplup", "empoleon"],
  empoleon: ["piplup", "prinplup", "empoleon"],
  starly: ["starly", "staravia", "staraptor"],
  staravia: ["starly", "staravia", "staraptor"],
  staraptor: ["starly", "staravia", "staraptor"],
  bidoof: ["bidoof", "bibarel"],
  bibarel: ["bidoof", "bibarel"],
  kricketot: ["kricketot", "kricketune"],
  kricketune: ["kricketot", "kricketune"],
  shinx: ["shinx", "luxio", "luxray"],
  luxio: ["shinx", "luxio", "luxray"],
  luxray: ["shinx", "luxio", "luxray"],
  budew: ["budew", "roselia", "roserade"],
  roserade: ["budew", "roselia", "roserade"],
  cranidos: ["cranidos", "rampardos"],
  rampardos: ["cranidos", "rampardos"],
  shieldon: ["shieldon", "bastiodon"],
  bastiodon: ["shieldon", "bastiodon"],
  burmy: ["burmy", "wormadam", "mothim"],
  wormadam: ["burmy", "wormadam", "mothim"],
  mothim: ["burmy", "wormadam", "mothim"],
  combee: ["combee", "vespiquen"],
  vespiquen: ["combee", "vespiquen"],
  pachirisu: ["pachirisu"],
  buizel: ["buizel", "floatzel"],
  floatzel: ["buizel", "floatzel"],
  cherubi: ["cherubi", "cherrim"],
  cherrim: ["cherubi", "cherrim"],
  shellos: ["shellos", "gastrodon"],
  gastrodon: ["shellos", "gastrodon"],
  ambipom: ["aipom", "ambipom"],
  drifloon: ["drifloon", "drifblim"],
  drifblim: ["drifloon", "drifblim"],
  buneary: ["buneary", "lopunny"],
  lopunny: ["buneary", "lopunny"],
  mismagius: ["misdreavus", "mismagius"],
  honchkrow: ["murkrow", "honchkrow"],
  glameow: ["glameow", "purugly"],
  purugly: ["glameow", "purugly"],
  chingling: ["chingling", "chimecho"],
  stunky: ["stunky", "skuntank"],
  skuntank: ["stunky", "skuntank"],
  bronzor: ["bronzor", "bronzong"],
  bronzong: ["bronzor", "bronzong"],
  bonsly: ["bonsly", "sudowoodo"],
  "mime jr.": ["mime jr.", "mr. mime"],
  happiny: ["happiny", "chansey", "blissey"],
  chatot: ["chatot"],
  spiritomb: ["spiritomb"],
  gible: ["gible", "gabite", "garchomp"],
  gabite: ["gible", "gabite", "garchomp"],
  garchomp: ["gible", "gabite", "garchomp"],
  munchlax: ["munchlax", "snorlax"],
  riolu: ["riolu", "lucario"],
  lucario: ["riolu", "lucario"],
  hippopotas: ["hippopotas", "hippowdon"],
  hippowdon: ["hippopotas", "hippowdon"],
  skorupi: ["skorupi", "drapion"],
  drapion: ["skorupi", "drapion"],
  croagunk: ["croagunk", "toxicroak"],
  toxicroak: ["croagunk", "toxicroak"],
  carnivine: ["carnivine"],
  finneon: ["finneon", "lumineon"],
  lumineon: ["finneon", "lumineon"],
  mantyke: ["mantyke", "mantine"],
  snover: ["snover", "abomasnow"],
  abomasnow: ["snover", "abomasnow"],
  weavile: ["sneasel", "weavile"],
  magnezone: ["magnemite", "magneton", "magnezone"],
  lickilicky: ["lickitung", "lickilicky"],
  rhyperior: ["rhyhorn", "rhydon", "rhyperior"],
  tangrowth: ["tangela", "tangrowth"],
  electivire: ["elekid", "electabuzz", "electivire"],
  magmortar: ["magby", "magmar", "magmortar"],
  togekiss: ["togepi", "togetic", "togekiss"],
  yanmega: ["yanma", "yanmega"],
  leafeon: ["eevee", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon"],
  glaceon: ["eevee", "vaporeon", "jolteon", "flareon", "espeon", "umbreon", "leafeon", "glaceon"],
  gliscor: ["gligar", "gliscor"],
  mamoswine: ["swinub", "piloswine", "mamoswine"],
  "porygon-z": ["porygon", "porygon2", "porygon-z"],
  probopass: ["nosepass", "probopass"],
  dusknoir: ["duskull", "dusclops", "dusknoir"],
  froslass: ["snorunt", "glalie", "froslass"],
  rotom: ["rotom"],

  // --- Unova ---
  snivy: ["snivy", "servine", "serperior"],
  servine: ["snivy", "servine", "serperior"],
  serperior: ["snivy", "servine", "serperior"],
  tepig: ["tepig", "pignite", "emboar"],
  pignite: ["tepig", "pignite", "emboar"],
  emboar: ["tepig", "pignite", "emboar"],
  oshawott: ["oshawott", "dewott", "samurott"],
  dewott: ["oshawott", "dewott", "samurott"],
  samurott: ["oshawott", "dewott", "samurott"],
  patrat: ["patrat", "watchog"],
  watchog: ["patrat", "watchog"],
  lillipup: ["lillipup", "herdier", "stoutland"],
  herdier: ["lillipup", "herdier", "stoutland"],
  stoutland: ["lillipup", "herdier", "stoutland"],
  purrloin: ["purrloin", "liepard"],
  liepard: ["purrloin", "liepard"],
  pansage: ["pansage", "simisage"],
  simisage: ["pansage", "simisage"],
  pansear: ["pansear", "simisear"],
  simisear: ["pansear", "simisear"],
  panpour: ["panpour", "simipour"],
  simipour: ["panpour", "simipour"],
  munna: ["munna", "musharna"],
  musharna: ["munna", "musharna"],
  pidove: ["pidove", "tranquill", "unfezant"],
  tranquill: ["pidove", "tranquill", "unfezant"],
  unfezant: ["pidove", "tranquill", "unfezant"],
  blitzle: ["blitzle", "zebstrika"],
  zebstrika: ["blitzle", "zebstrika"],
  roggenrola: ["roggenrola", "boldore", "gigalith"],
  boldore: ["roggenrola", "boldore", "gigalith"],
  gigalith: ["roggenrola", "boldore", "gigalith"],
  woobat: ["woobat", "swoobat"],
  swoobat: ["woobat", "swoobat"],
  drilbur: ["drilbur", "excadrill"],
  excadrill: ["drilbur", "excadrill"],
  audino: ["audino"],
  timburr: ["timburr", "gurdurr", "conkeldurr"],
  gurdurr: ["timburr", "gurdurr", "conkeldurr"],
  conkeldurr: ["timburr", "gurdurr", "conkeldurr"],
  tympole: ["tympole", "palpitoad", "seismitoad"],
  palpitoad: ["tympole", "palpitoad", "seismitoad"],
  seismitoad: ["tympole", "palpitoad", "seismitoad"],
  throh: ["throh"],
  sawk: ["sawk"],
  sewaddle: ["sewaddle", "swadloon", "leavanny"],
  swadloon: ["sewaddle", "swadloon", "leavanny"],
  leavanny: ["sewaddle", "swadloon", "leavanny"],
  venipede: ["venipede", "whirlipede", "scolipede"],
  whirlipede: ["venipede", "whirlipede", "scolipede"],
  scolipede: ["venipede", "whirlipede", "scolipede"],
  cottonee: ["cottonee", "whimsicott"],
  whimsicott: ["cottonee", "whimsicott"],
  petilil: ["petilil", "lilligant"],
  lilligant: ["petilil", "lilligant"],
  basculin: ["basculin"],
  sandile: ["sandile", "krokorok", "krookodile"],
  krokorok: ["sandile", "krokorok", "krookodile"],
  krookodile: ["sandile", "krokorok", "krookodile"],
  darumaka: ["darumaka", "darmanitan"],
  darmanitan: ["darumaka", "darmanitan"],
  maractus: ["maractus"],
  dwebble: ["dwebble", "crustle"],
  crustle: ["dwebble", "crustle"],
  scraggy: ["scraggy", "scrafty"],
  scrafty: ["scraggy", "scrafty"],
  sigilyph: ["sigilyph"],
  yamask: ["yamask", "cofagrigus"],
  cofagrigus: ["yamask", "cofagrigus"],
  tirtouga: ["tirtouga", "carracosta"],
  carracosta: ["tirtouga", "carracosta"],
  archen: ["archen", "archeops"],
  archeops: ["archen", "archeops"],
  trubbish: ["trubbish", "garbodor"],
  garbodor: ["trubbish", "garbodor"],
  zorua: ["zorua", "zoroark"],
  zoroark: ["zorua", "zoroark"],
  minccino: ["minccino", "cinccino"],
  cinccino: ["minccino", "cinccino"],
  gothita: ["gothita", "gothorita", "gothitelle"],
  gothorita: ["gothita", "gothorita", "gothitelle"],
  gothitelle: ["gothita", "gothorita", "gothitelle"],
  solosis: ["solosis", "duosion", "reuniclus"],
  duosion: ["solosis", "duosion", "reuniclus"],
  reuniclus: ["solosis", "duosion", "reuniclus"],
  ducklett: ["ducklett", "swanna"],
  swanna: ["ducklett", "swanna"],
  vanillite: ["vanillite", "vanillish", "vanilluxe"],
  vanillish: ["vanillite", "vanillish", "vanilluxe"],
  vanilluxe: ["vanillite", "vanillish", "vanilluxe"],
  deerling: ["deerling", "sawsbuck"],
  sawsbuck: ["deerling", "sawsbuck"],
  emolga: ["emolga"],
  karrablast: ["karrablast", "escavalier"],
  escavalier: ["karrablast", "escavalier"],
  foongus: ["foongus", "amoonguss"],
  amoonguss: ["foongus", "amoonguss"],
  frillish: ["frillish", "jellicent"],
  jellicent: ["frillish", "jellicent"],
  alomomola: ["alomomola"],
  joltik: ["joltik", "galvantula"],
  galvantula: ["joltik", "galvantula"],
  ferroseed: ["ferroseed", "ferrothorn"],
  ferrothorn: ["ferroseed", "ferrothorn"],
  klink: ["klink", "klang", "klinklang"],
  klang: ["klink", "klang", "klinklang"],
  klinklang: ["klink", "klang", "klinklang"],
  tynamo: ["tynamo", "eelektrik", "eelektross"],
  eelektrik: ["tynamo", "eelektrik", "eelektross"],
  eelektross: ["tynamo", "eelektrik", "eelektross"],
  elgyem: ["elgyem", "beheeyem"],
  beheeyem: ["elgyem", "beheeyem"],
  litwick: ["litwick", "lampent", "chandelure"],
  lampent: ["litwick", "lampent", "chandelure"],
  chandelure: ["litwick", "lampent", "chandelure"],
  axew: ["axew", "fraxure", "haxorus"],
  fraxure: ["axew", "fraxure", "haxorus"],
  haxorus: ["axew", "fraxure", "haxorus"],
  cubchoo: ["cubchoo", "beartic"],
  beartic: ["cubchoo", "beartic"],
  cryogonal: ["cryogonal"],
  shelmet: ["shelmet", "accelgor"],
  accelgor: ["shelmet", "accelgor"],
  stunfisk: ["stunfisk"],
  mienfoo: ["mienfoo", "mienshao"],
  mienshao: ["mienfoo", "mienshao"],
  druddigon: ["druddigon"],
  golett: ["golett", "golurk"],
  golurk: ["golett", "golurk"],
  pawniard: ["pawniard", "bisharp"],
  bisharp: ["pawniard", "bisharp"],
  bouffalant: ["bouffalant"],
  rufflet: ["rufflet", "braviary"],
  braviary: ["rufflet", "braviary"],
  vullaby: ["vullaby", "mandibuzz"],
  mandibuzz: ["vullaby", "mandibuzz"],
  heatmor: ["heatmor"],
  durant: ["durant"],
  deino: ["deino", "zweilous", "hydreigon"],
  zweilous: ["deino", "zweilous", "hydreigon"],
  hydreigon: ["deino", "zweilous", "hydreigon"],
  larvesta: ["larvesta", "volcarona"],
  volcarona: ["larvesta", "volcarona"]
};

// --- Normalized aliases for all families (handles Nidoran and any other special case) ---
Object.keys(window.pokemonFamilies).forEach(key => {
  let norm = key.toLowerCase()
    .replace(/♀/g,"-f")
    .replace(/♂/g,"-m")
    .replace(/[- '\.’]/g,"")
    .trim();
  if (norm !== key && !window.pokemonFamilies[norm]) {
    window.pokemonFamilies[norm] = window.pokemonFamilies[key];
  }
});
