// Full Shiny Dex list for Team Shroom, with all claims
const shinyDex = {
  Kanto: [
    { name: "Bulbasaur", claimed: "WillyPS" },
    { name: "Ivysaur", claimed: false },
    { name: "Venusaur", claimed: false },
    { name: "Charmander", claimed: "Slowshiny" },
    { name: "Charmeleon", claimed: "OhitsDunco" },
    { name: "Charizard", claimed: "Smokycat" },
    { name: "Squirtle", claimed: "WillyPS" },
    { name: "Wartortle", claimed: "Draind" },
    { name: "Blastoise", claimed: false },
    { name: "Caterpie", claimed: "LordGangis" },
    { name: "Metapod", claimed: "HokeyMMO" },
    { name: "Butterfree", claimed: "skyeatsme" },
    { name: "Weedle", claimed: "Tortuponchy" },
    { name: "Kakuna", claimed: "HokeyMMO" },
    { name: "Beedrill", claimed: "RuthlessZ" },
    { name: "Pidgey", claimed: "BabyLime" },
    { name: "Pidgeotto", claimed: "BabyLime" },
    { name: "Pidgeot", claimed: "BabyLime" },
    { name: "Rattata", claimed: "Bulkanator" },
    { name: "Raticate", claimed: "LunaLost" },
    { name: "Spearow", claimed: "Serako" },
    { name: "Fearow", claimed: "skyeatsme" },
    { name: "Ekans", claimed: "DaddyMolo" },
    { name: "Arbok", claimed: "ShonoMcD" },
    { name: "Pikachu", claimed: "HokeyMMO" },
    { name: "Raichu", claimed: "Terminus" },
    { name: "Sandshrew", claimed: "SmiigZ" },
    { name: "Sandslash", claimed: "TrainerBartos" },
    { name: "Nidoran♀", claimed: "OhItsDunco" },
    { name: "Nidorina", claimed: "HokeyMMO", },
    { name: "Nidoqueen", claimed: "Dupe" },
    { name: "Nidoran♂", claimed: "HokeyMMO" },
    { name: "Nidorino", claimed: "SphealMyWrath" },
    { name: "Nidoking", claimed: "Dupe" },
    { name: "Clefairy", claimed: "Slowshiny" },
    { name: "Clefable", claimed: "HokeyMMO" },
    { name: "Vulpix", claimed: "Highschoolme" },
    { name: "Ninetales", claimed: "HokeyMMO" },
    { name: "Jigglypuff", claimed: "HokeyMMO" },
    { name: "Wigglytuff", claimed: "Terminus" },
    { name: "Zubat", claimed: "Darktrench" },
    { name: "Golbat", claimed: "egoPraise" },
    { name: "Oddish", claimed: "skyeatsme" },
    { name: "Gloom", claimed: "HokeyMMO" },
    { name: "Vileplume", claimed: "Darktrench" },
    { name: "Paras", claimed: "skyeatsme" },
    { name: "Parasect", claimed: "SmiigZ" },
    { name: "Venonat", claimed: false },
    { name: "Venomoth", claimed: false },
    { name: "Diglett", claimed: "maknaez" },
    { name: "Dugtrio", claimed: "EgoPraise" },
    { name: "Meowth", claimed: "MitchOsu" },
    { name: "Persian", claimed: "skyeatsme" },
    { name: "Psyduck", claimed: "OrllandoV" },
    { name: "Golduck", claimed: "Wisqi" },
    { name: "Mankey", claimed: "Bulkanator", },
    { name: "Primeape", claimed: "drownsyy" },
    { name: "Growlithe", claimed: "HokeyMMO" },
    { name: "Arcanine", claimed: "TheJuanNonly" },
    { name: "Poliwag", claimed: "SphealMyWrath" },
    { name: "Poliwhirl", claimed: "maknaez" },
    { name: "Poliwrath", claimed: "Lord Gangis" },
    { name: "Abra", claimed: "HokeyMMO"  },
    { name: "Kadabra", claimed: "Loundemon" },
    { name: "Alakazam", claimed: "BojanglesisHere" },
    { name: "Machop", claimed: "HokeyMMO" },
    { name: "Machoke", claimed: "Wisqi" },
    { name: "Machamp", claimed: "Bulkanator" },
    { name: "Bellsprout", claimed: "PaulusTFT" },
    { name: "Weepinbell", claimed: "HokeyMMO" },
    { name: "Victreebel", claimed: "Darktrench" },
    { name: "Tentacool", claimed: "skyeatsme" },
    { name: "Tentacruel", claimed: "HokeyMMO" },
    { name: "Geodude", claimed: "BUSTHETHOMAS" },
    { name: "Graveler", claimed: "BUSTHETHOMAS" },
    { name: "Golem", claimed: "Splinterbrained" },
    { name: "Ponyta", claimed: "JazxB" },
    { name: "Rapidash", claimed: "Loundemon" },
    { name: "Slowpoke", claimed: "HokeyMMO" },
    { name: "Slowbro", claimed: "OhitsDunco" },
    { name: "Magnemite", claimed: "Darktrench" },
    { name: "Magneton", claimed: false },
    { name: "Farfetch’d", claimed: false },
    { name: "Doduo", claimed: "SphealMyWrath" },
    { name: "Dodrio", claimed: "KenGriffsJr" },
    { name: "Seel", claimed: false },
    { name: "Dewgong", claimed: false },
    { name: "Grimer", claimed: "stevenchill" },
    { name: "Muk", claimed: "BrodyBones" },
    { name: "Shellder", claimed: "skyeatsme" },
    { name: "Cloyster", claimed: "brdleys" },
    { name: "Gastly", claimed: "BUSTHETHOMAS" },
    { name: "Haunter", claimed: "maknaez" },
    { name: "Gengar", claimed: "HokeyMMO" },
    { name: "Onix", claimed: "maknaez" },
    { name: "Drowzee", claimed: "skyeatsme" },
    { name: "Hypno", claimed: "pearishx" },
    { name: "Krabby", claimed: "WillyPS" },
    { name: "Kingler", claimed: false },
    { name: "Voltorb", claimed: "PaulusTFT" },
    { name: "Electrode", claimed: false },
    { name: "Exeggcute", claimed: false },
    { name: "Exeggutor", claimed: false },
    { name: "Cubone", claimed: "ShakeyEy" },
    { name: "Marowak", claimed: "skyeatsme" },
    { name: "Hitmonlee", claimed: false },
    { name: "Hitmonchan", claimed: false },
    { name: "Lickitung", claimed: false },
    { name: "Koffing", claimed: "LilAF" },
    { name: "Weezing", claimed: "ShakeyEY" },
    { name: "Rhyhorn", claimed: "Slowshiny" },
    { name: "Rhydon", claimed: "ZiaStitch" },
    { name: "Chansey", claimed: "Draind" },
    { name: "Tangela", claimed: "WillyPS" },
    { name: "Kangaskhan", claimed: false },
    { name: "Horsea", claimed: "CraazyHorse" },
    { name: "Seadra", claimed: "SphealMyWrath" },
    { name: "Goldeen", claimed: false },
    { name: "Seaking", claimed: "OrllandoV" },
    { name: "Staryu", claimed: "Jutskaa" },
    { name: "Starmie", claimed: false },
    { name: "Mr. Mime", claimed: false },
    { name: "Scyther", claimed: "Smokycat" },
    { name: "Jynx", claimed: false },
    { name: "Electabuzz", claimed: false },
    { name: "Magmar", claimed: "ShakeyEy" },
    { name: "Pinsir", claimed: "Hjordi" },
    { name: "Tauros", claimed: false },
    { name: "Magikarp", claimed: "UltraKingRom" },
    { name: "Gyarados", claimed: "maknaez" },
    { name: "Lapras", claimed: false },
    { name: "Ditto", claimed: "Instintooo" },
    { name: "Eevee", claimed: "WillyPS" },
    { name: "Vaporeon", claimed: "WillyPS" },
    { name: "Jolteon", claimed: "MeBrine" },
    { name: "Flareon", claimed: false },
    { name: "Porygon", claimed: false },
    { name: "Omanyte", claimed: false },
    { name: "Omastar", claimed: false },
    { name: "Kabuto", claimed: false },
    { name: "Kabutops", claimed: false },
    { name: "Aerodactyl", claimed: false },
    { name: "Snorlax", claimed: "Pangeaa" },
    { name: "Articuno", claimed: false },
    { name: "Zapdos", claimed: false },
    { name: "Moltres", claimed: false },
    { name: "Dratini", claimed: "maknaez" },
    { name: "Dragonair", claimed: "LordGangis" },
    { name: "Dragonite", claimed: "HokeyMMO" }
  ],
  Johto: [
    { name: "Chikorita", claimed: false },
    { name: "Bayleef", claimed: false },
    { name: "Meganium", claimed: false },
    { name: "Cyndaquil", claimed: "stevenchill" },
    { name: "Quilava", claimed: false },
    { name: "Typhlosion", claimed: false },
    { name: "Totodile", claimed: false },
    { name: "Croconaw", claimed: false },
    { name: "Feraligatr", claimed: false },
    { name: "Sentret", claimed: false },
    { name: "Furret", claimed: false },
    { name: "Hoothoot", claimed: "DaddyMolo" },
    { name: "Noctowl", claimed: "TTVxSenseiNESS" },
    { name: "Ledyba", claimed: false },
    { name: "Ledian", claimed: false },
    { name: "Spinarak", claimed: false },
    { name: "Ariados", claimed: false },
    { name: "Crobat", claimed: "Gumbasketball" },
    { name: "Chinchou", claimed: "SphealMyWrath" },
    { name: "Lanturn", claimed: "LordGangis" },
    { name: "Pichu", claimed: "MELVZZY" },
    { name: "Cleffa", claimed: "Jutskaa" },
    { name: "Igglybuff", claimed: "Hjordi" },
    { name: "Togepi", claimed: false },
    { name: "Togetic", claimed: "Eerie" },
    { name: "Natu", claimed: "skyeatsme" },
    { name: "Xatu", claimed: "skyeatsme" },
    { name: "Mareep", claimed: "DaddyMolo" },
    { name: "Flaaffy", claimed: "OhitsDunco" },
    { name: "Ampharos", claimed: "Terminus" },
    { name: "Bellossom", claimed: "Dupe" },
    { name: "Marill", claimed: "Unesha" },
    { name: "Azumarill", claimed: "LilAF" },
    { name: "Sudowoodo", claimed: "Smokycat" },
    { name: "Politoed", claimed: "ZiaStitch" },
    { name: "Hoppip", claimed: "SkiddyPoo" },
    { name: "Skiploom", claimed: false },
    { name: "Jumpluff", claimed: false },
    { name: "Aipom", claimed: "clairo" },
    { name: "Sunkern", claimed: "Bulkanator" },
    { name: "Sunflora", claimed: false },
    { name: "Yanma", claimed: false },
    { name: "Wooper", claimed: "BUSTHETHOMAS" },
    { name: "Quagsire", claimed: "SphealMyWrath" },
    { name: "Espeon", claimed: false },
    { name: "Umbreon", claimed: false },
    { name: "Murkrow", claimed: "Splinterbrained" },
    { name: "Slowking", claimed: "DaddyMolo" },
    { name: "Misdreavus", claimed: "EgoPraise" },
    { name: "Unown", claimed: false },
    { name: "Wobbuffet", claimed: false },
    { name: "Girafarig", claimed: "MikeRunkZz" },
    { name: "Pineco", claimed: false },
    { name: "Forretress", claimed: false },
    { name: "Dunsparce", claimed: false },
    { name: "Gligar", claimed: "BUSTHETHOMAS" },
    { name: "Steelix", claimed: "maknaez" },
    { name: "Snubbull", claimed: false },
    { name: "Granbull", claimed: false },
    { name: "Qwilfish", claimed: false },
    { name: "Scizor", claimed: false },
    { name: "Shuckle", claimed: false },
    { name: "Heracross", claimed: "Sirbeyy" },
    { name: "Sneasel", claimed: "Lodarko" },
    { name: "Teddiursa", claimed: "Hjordi" },
    { name: "Ursaring", claimed: "QuinJay" },
    { name: "Slugma", claimed: "Lodarko" },
    { name: "Magcargo", claimed: "TorontoKid" },
    { name: "Swinub", claimed: false },
    { name: "Piloswine", claimed: "Wisqi" },
    { name: "Corsola", claimed: false },
    { name: "Remoraid", claimed: "JazxB" },
    { name: "Octillery", claimed: "Smokycat" },
    { name: "Delibird", claimed: false },
    { name: "Mantine", claimed: "nerfviands" },
    { name: "Skarmory", claimed: "ShakeyEy" },
    { name: "Houndour", claimed: "Sirbeyy" },
    { name: "Houndoom", claimed: "Darktrench" },
    { name: "Kingdra", claimed: "Darktrench" },
    { name: "Phanpy", claimed: "Grrzzly" },
    { name: "Donphan", claimed: "KenGriffsJr" },
    { name: "Porygon2", claimed: false },
    { name: "Stantler", claimed: false },
    { name: "Smeargle", claimed: "MELVZZY" },
    { name: "Tyrogue", claimed: false },
    { name: "Hitmontop", claimed: false },
    { name: "Smoochum", claimed: false },
    { name: "Elekid", claimed: false },
    { name: "Magby", claimed: false },
    { name: "Miltank", claimed: "PaulusTFT" },
    { name: "Blissey", claimed: false },
    { name: "Raikou", claimed: false },
    { name: "Entei", claimed: false },
    { name: "Suicune", claimed: false },
    { name: "Larvitar", claimed: "Serako" },
    { name: "Pupitar", claimed: "Darktrench" },
    { name: "Tyranitar", claimed: "SkiddyPoo" }
  ],
  Hoenn: [
    { name: "Treecko", claimed: "Jeakama" },
    { name: "Grovyle", claimed: "Prttyflxcko" },
    { name: "Sceptile", claimed: false },
    { name: "Torchic", claimed: false },
    { name: "Combusken", claimed: false },
    { name: "Blaziken", claimed: false },
    { name: "Mudkip", claimed: "KrikaDoce" },
    { name: "Marshtomp", claimed: false },
    { name: "Swampert", claimed: false },
    { name: "Poochyena", claimed: "BabyLime" },
    { name: "Mightyena", claimed: "skyeatsme" },
    { name: "Zigzagoon", claimed: "Slowshiny" },
    { name: "Linoone", claimed: "qtAlice" },
    { name: "Wurmple", claimed: "skyeatsme" },
    { name: "Silcoon", claimed: "Jeakama" },
    { name: "Beautifly", claimed: "DamoNll" },
    { name: "Cascoon", claimed: "TrainerBartos" },
    { name: "Dustox", claimed: "Sirbeyy" },
    { name: "Lotad", claimed: "Darktrench" },
    { name: "Lombre", claimed: "SphealMyWrath" },
    { name: "Ludicolo", claimed: "skyeatsme" },
    { name: "Seedot", claimed: "tardigreat" },
    { name: "Nuzleaf", claimed: false },
    { name: "Shiftry", claimed: false },
    { name: "Taillow", claimed: "qtAlice" },
    { name: "Swellow", claimed: "qtAlice" },
    { name: "Wingull", claimed: "stevenchill" },
    { name: "Pelipper", claimed: "Jutskaa" },
    { name: "Ralts", claimed: "Draind" },
    { name: "Kirlia", claimed: "GTGxR" },
    { name: "Gardevoir", claimed: "Hjordi" },
    { name: "Surskit", claimed: "SmiigZ" },
    { name: "Masquerain", claimed: false },
    { name: "Shroomish", claimed: "clairofan" },
    { name: "Breloom", claimed: "WillyPS" },
    { name: "Slakoth", claimed: "GumBasketball" },
    { name: "Vigoroth", claimed: false },
    { name: "Slaking", claimed: false },
    { name: "Nincada", claimed: false },
    { name: "Ninjask", claimed: false },
    { name: "Shedinja", claimed: "pearishx" },
    { name: "Whismur", claimed: "JulieJewel" },
    { name: "Loudred", claimed: "xCOPYCATx" },
    { name: "Exploud", claimed: false },
    { name: "Makuhita", claimed: false },
    { name: "Hariyama", claimed: false },
    { name: "Azurill", claimed: "SphealMyWrath" },
    { name: "Nosepass", claimed: false },
    { name: "Skitty", claimed: false },
    { name: "Delcatty", claimed: false },
    { name: "Sableye", claimed: "KenGriffsJr" },
    { name: "Mawile", claimed: "TrainerBartos" },
    { name: "Aron", claimed: "SphealMyWrath" },
    { name: "Lairon", claimed: "Sapiane" },
    { name: "Aggron", claimed: "jaspn" },
    { name: "Meditite", claimed: false },
    { name: "Medicham", claimed: false },
    { name: "Electrike", claimed: false },
    { name: "Manectric", claimed: false },
    { name: "Plusle", claimed: false },
    { name: "Minun", claimed: false },
    { name: "Volbeat", claimed: false },
    { name: "Illumise", claimed: false },
    { name: "Roselia", claimed: "LoDarko" },
    { name: "Gulpin", claimed: false },
    { name: "Swalot", claimed: false },
    { name: "Carvanha", claimed: "pearishx" },
    { name: "Sharpedo", claimed: "pearishx" },
    { name: "Wailmer", claimed: "SkiddyPoo" },
    { name: "Wailord", claimed: "JGrenade" },
    { name: "Numel", claimed: "Hjordi" },
    { name: "Camerupt", claimed: "ShonoMcD" },
    { name: "Torkoal", claimed: "LordGangis" },
    { name: "Spoink", claimed: "SphealMyWrath" },
    { name: "Grumpig", claimed: false },
    { name: "Spinda", claimed: "maknaez" },
    { name: "Trapinch", claimed: "stevenchill" },
    { name: "Vibrava", claimed: "ShakeyEy" },
    { name: "Flygon", claimed: "Hjordi" },
    { name: "Cacnea", claimed: "LoDarko" },
    { name: "Cacturne", claimed: false },
    { name: "Swablu", claimed: "HokeyMMO" },
    { name: "Altaria", claimed: "ZiaStitch" },
    { name: "Zangoose", claimed: "stevenchill" },
    { name: "Seviper", claimed: false },
    { name: "Lunatone", claimed: "EgoPraise" },
    { name: "Solrock", claimed: "maknaez" },
    { name: "Barboach", claimed: false },
    { name: "Whiscash", claimed: false },
    { name: "Corphish", claimed: "LordGangis" },
    { name: "Crawdaunt", claimed: "Sirbeyy" },
    { name: "Baltoy", claimed: false },
    { name: "Claydol", claimed: "Eerie" },
    { name: "Lileep", claimed: false },
    { name: "Cradily", claimed: false },
    { name: "Anorith", claimed: false },
    { name: "Armaldo", claimed: false },
    { name: "Feebas", claimed: false },
    { name: "Milotic", claimed: false },
    { name: "Castform", claimed: false },
    { name: "Kecleon", claimed: "BojanglesisHere" },
    { name: "Shuppet", claimed: "Stevenchill" },
    { name: "Banette", claimed: "LilAF" },
    { name: "Duskull", claimed: "LordGangis" },
    { name: "Dusclops", claimed: "TorontoKid" },
    { name: "Tropius", claimed: "Sirbeyy" },
    { name: "Chimecho", claimed: false },
    { name: "Absol", claimed: "SkiddyPoo" },
    { name: "Wynaut", claimed: false },
    { name: "Snorunt", claimed: false },
    { name: "Glalie", claimed: false },
    { name: "Spheal", claimed: "TheStahlBayBay" },
    { name: "Sealeo", claimed: "SphealMyWrath" },
    { name: "Walrein", claimed: "TorontoKid" },
    { name: "Clamperl", claimed: "SphealMyWrath" },
    { name: "Huntail", claimed: false },
    { name: "Gorebyss", claimed: false },
    { name: "Relicanth", claimed: false },
    { name: "Luvdisc", claimed: false },
    { name: "Bagon", claimed: "maknaez" },
    { name: "Shelgon", claimed: "LunaLost" },
    { name: "Salamence", claimed: "zzxyami" },
    { name: "Beldum", claimed: "maknaez" },
    { name: "Metang", claimed: false },
    { name: "Metagross", claimed: false }
  ],
  Sinnoh: [
    { name: "Turtwig", claimed: false },
    { name: "Grotle", claimed: false },
    { name: "Torterra", claimed: false },
    { name: "Chimchar", claimed: false },
    { name: "Monferno", claimed: false },
    { name: "Infernape", claimed: false },
    { name: "Piplup", claimed: false },
    { name: "Prinplup", claimed: false },
    { name: "Empoleon", claimed: false },
    { name: "Starly", claimed: false },
    { name: "Staravia", claimed: "Eerie" },
    { name: "Staraptor", claimed: false },
    { name: "Bidoof", claimed: "Draind" },
    { name: "Bibarel", claimed: "maknaez" },
    { name: "Kricketot", claimed: false },
    { name: "Kricketune", claimed: false },
    { name: "Shinx", claimed: "Hjordi" },
    { name: "Luxio", claimed: "stevenchill" },
    { name: "Luxray", claimed: false },
    { name: "Budew", claimed: false },
    { name: "Roserade", claimed: false },
    { name: "Cranidos", claimed: false },
    { name: "Rampardos", claimed: false },
    { name: "Shieldon", claimed: false },
    { name: "Bastiodon", claimed: false },
    { name: "Burmy", claimed: false },
    { name: "Wormadam", claimed: false },
    { name: "Mothim", claimed: false },
    { name: "Combee", claimed: "BojanglesisHere" },
    { name: "Vespiquen", claimed: false },
    { name: "Pachirisu", claimed: false },
    { name: "Buizel", claimed: "Eerie" },
    { name: "Floatzel", claimed: "LunaLost" },
    { name: "Cherubi", claimed: false },
    { name: "Cherrim", claimed: false },
    { name: "Shellos", claimed: "Darktrench" },
    { name: "Gastrodon", claimed: "TTVxSenseiNESS" },
    { name: "Ambipom", claimed: "WillyPS" },
    { name: "Drifloon", claimed: false },
    { name: "Drifblim", claimed: false },
    { name: "Buneary", claimed: "pearishx" },
    { name: "Lopunny", claimed: "Srysu" },
    { name: "Mismagius", claimed: "Gumbasketball" },
    { name: "Honchkrow", claimed: "OrllandoV" },
    { name: "Glameow", claimed: false },
    { name: "Purugly", claimed: false },
    { name: "Chingling", claimed: false },
    { name: "Stunky", claimed: "PaulusTFT" },
    { name: "Skuntank", claimed: false },
    { name: "Bronzor", claimed: false },
    { name: "Bronzong", claimed: "LordGangis" },
    { name: "Bonsly", claimed: false },
    { name: "Mime Jr.", claimed: false },
    { name: "Happiny", claimed: false },
    { name: "Chatot", claimed: false },
    { name: "Spiritomb", claimed: "pearishx" },
    { name: "Gible", claimed: "LunaLost" },
    { name: "Gabite", claimed: "Darktrench" },
    { name: "Garchomp", claimed: "Eerie" },
    { name: "Munchlax", claimed: false },
    { name: "Riolu", claimed: false },
    { name: "Lucario", claimed: false },
    { name: "Hippopotas", claimed: false },
    { name: "Hippowdon", claimed: false },
    { name: "Skorupi", claimed: false },
    { name: "Drapion", claimed: false },
    { name: "Croagunk", claimed: false },
    { name: "Toxicroak", claimed: false },
    { name: "Carnivine", claimed: false },
    { name: "Finneon", claimed: false },
    { name: "Lumineon", claimed: false },
    { name: "Mantyke", claimed: "Hjordi" },
    { name: "Snover", claimed: "skyeatsme" },
    { name: "Abomasnow", claimed: "LoDarko" },
    { name: "Weavile", claimed: "Darktrench" },
    { name: "Magnezone", claimed: false },
    { name: "Lickilicky", claimed: false },
    { name: "Rhyperior", claimed: "MitchOsu" },
    { name: "Tangrowth", claimed: "Tulicreme" },
    { name: "Electivire", claimed: "OhItsDunco" },
    { name: "Magmortar", claimed: false },
    { name: "Togekiss", claimed: false },
    { name: "Yanmega", claimed: false },
    { name: "Leafeon", claimed: false },
    { name: "Glaceon", claimed: false },
    { name: "Gliscor", claimed: "LilAF" },
    { name: "Mamoswine", claimed: false },
    { name: "Porygon-Z", claimed: false },
    { name: "Gallade", claimed: "XxEmperiorxX" },
    { name: "Probopass", claimed: false },
    { name: "Dusknoir", claimed: "jaspn" },
    { name: "Froslass", claimed: false },
    { name: "Rotom", claimed: false },
    { name: "Heatran", claimed: false },
    { name: "Shaymin", claimed: false }
  ],
  Unova: [
    { name: "Snivy", claimed: false },
    { name: "Servine", claimed: false },
    { name: "Serperior", claimed: false },
    { name: "Tepig", claimed: false },
    { name: "Pignite", claimed: false },
    { name: "Emboar", claimed: false },
    { name: "Oshawott", claimed: false },
    { name: "Dewott", claimed: false },
    { name: "Samurott", claimed: false },
    { name: "Patrat", claimed: false },
    { name: "Watchog", claimed: "Jutskaa" },
    { name: "Lillipup", claimed: "Jutskaa" },
    { name: "Herdier", claimed: false },
    { name: "Stoutland", claimed: false },
    { name: "Purrloin", claimed: "YaHKnOmE" },
    { name: "Liepard", claimed: "Wisqi" },
    { name: "Pansage", claimed: false },
    { name: "Simisage", claimed: false },
    { name: "Pansear", claimed: false },
    { name: "Simisear", claimed: false },
    { name: "Panpour", claimed: false },
    { name: "Simipour", claimed: false },
    { name: "Munna", claimed: false },
    { name: "Musharna", claimed: false },
    { name: "Pidove", claimed: "OhItsDunco" },
    { name: "Tranquill", claimed: "YaHKnOmE" },
    { name: "Unfezant", claimed: "ItsKitas" },
    { name: "Blitzle", claimed: false },
    { name: "Zebstrika", claimed: false },
    { name: "Roggenrola", claimed: "Slowshiny" },
    { name: "Boldore", claimed: "Slowshiny" },
    { name: "Gigalith", claimed: false },
    { name: "Woobat", claimed: "stevenchill" },
    { name: "Swoobat", claimed: "stevenchill" },
    { name: "Drilbur", claimed: "Draind" },
    { name: "Excadrill", claimed: "PaulusTFT" },
    { name: "Audino", claimed: false },
    { name: "Timburr", claimed: "KenGriffsuJr" },
    { name: "Gurdurr", claimed: "LordGangis" },
    { name: "Conkeldurr", claimed: false },
    { name: "Tympole", claimed: false },
    { name: "Palpitoad", claimed: "Drizzle" },
    { name: "Seismitoad", claimed: false },
    { name: "Throh", claimed: false },
    { name: "Sawk", claimed: false },
    { name: "Sewaddle", claimed: "Drownsyy" },
    { name: "Swadloon", claimed: "SmiigZ" },
    { name: "Leavanny", claimed: "HokeyMMO" },
    { name: "Venipede", claimed: "TTVxSenseiNESS" },
    { name: "Whirlipede", claimed: "TTVxSenseiNESS" },
    { name: "Scolipede", claimed: "stevenchill" },
    { name: "Cottonee", claimed: "Blistik" },
    { name: "Whimsicott", claimed: "Sirbeyy" },
    { name: "Petilil", claimed: "TTVxSenseiNESS" },
    { name: "Lilligant", claimed: "ItsHypers" },
    { name: "Basculin", claimed: "DaddyMolo" },
    { name: "Sandile", claimed: "skyeatsme" },
    { name: "Krokorok", claimed: "Yoyoyoshie" },
    { name: "Krookodile", claimed: "SmiigZ" },
    { name: "Darumaka", claimed: "egoPraise" },
    { name: "Darmanitan", claimed: false },
    { name: "Maractus", claimed: false },
    { name: "Dwebble", claimed: false },
    { name: "Crustle", claimed: false },
    { name: "Scraggy", claimed: "Dupe" },
    { name: "Scrafty", claimed: "Jayyxxi" },
    { name: "Sigilyph", claimed: false },
    { name: "Yamask", claimed: false },
    { name: "Cofagrigus", claimed: "LordGangis" },
    { name: "Tirtouga", claimed: false },
    { name: "Carracosta", claimed: false },
    { name: "Archen", claimed: false },
    { name: "Archeops", claimed: false },
    { name: "Trubbish", claimed: false },
    { name: "Garbodor", claimed: false },
    { name: "Zorua", claimed: false },
    { name: "Zoroark", claimed: false },
    { name: "Minccino", claimed: "Grrzzly" },
    { name: "Cinccino", claimed: "TorontoKid" },
    { name: "Gothita", claimed: false },
    { name: "Gothorita", claimed: false },
    { name: "Gothitelle", claimed: false },
    { name: "Solosis", claimed: "LilAF" },
    { name: "Duosion", claimed: "LordGangis" },
    { name: "Reuniclus", claimed: "Darktrench" },
    { name: "Ducklett", claimed: "DaddyMolo" },
    { name: "Swanna", claimed: "Dupe" },
    { name: "Vanillite", claimed: "OhitsDunco" },
    { name: "Vanillish", claimed: "TorontoKid" },
    { name: "Vanilluxe", claimed: "DaddyMolo" },
    { name: "Deerling", claimed: false },
    { name: "Sawsbuck", claimed: false },
    { name: "Emolga", claimed: false },
    { name: "Karrablast", claimed: false },
    { name: "Escavalier", claimed: false },
    { name: "Foongus", claimed: "SkiddyPoo" },
    { name: "Amoonguss", claimed: "skyeatsme" },
    { name: "Frillish", claimed: "TTVxSenseiNESS" },
    { name: "Jellicent", claimed: "Darktrench" },
    { name: "Alomomola", claimed: false },
    { name: "Joltik", claimed: "LilAF" },
    { name: "Galvantula", claimed: "LilAF" },
    { name: "Ferroseed", claimed: "DaddyMolo" },
    { name: "Ferrothorn", claimed: "OhitsDunco" },
    { name: "Klink", claimed: "Drizzle" },
    { name: "Klang", claimed: "LilAF" },
    { name: "Klinklang", claimed: "LilAF" },
    { name: "Tynamo", claimed: false },
    { name: "Eelektrik", claimed: false },
    { name: "Eelektross", claimed: false },
    { name: "Elgyem", claimed: false },
    { name: "Beheeyem", claimed: false },
    { name: "Litwick", claimed: "OhitsDunco" },
    { name: "Lampent", claimed: "stevenchill" },
    { name: "Chandelure", claimed: "LilAF" },
    { name: "Axew", claimed: "cuteasduckk" },
    { name: "Fraxure", claimed: "stevenchill" },
    { name: "Haxorus", claimed: "stevenchill" },
    { name: "Cubchoo", claimed: "ShakeyEy" },
    { name: "Beartic", claimed: "Dupe" },
    { name: "Cryogonal", claimed: "Johnerrr" },
    { name: "Shelmet", claimed: "KenGriffsuJr" },
    { name: "Accelgor", claimed: "ZiaStitch" },
    { name: "Stunfisk", claimed: false },
    { name: "Mienfoo", claimed: "Darktrench" },
    { name: "Mienshao", claimed: "Dupe" },
    { name: "Druddigon", claimed: false },
    { name: "Golett", claimed: "Stevenchill" },
    { name: "Golurk", claimed: "skyeatsme" },
    { name: "Pawniard", claimed: false },
    { name: "Bisharp", claimed: false },
    { name: "Bouffalant", claimed: "DaddyMolo" },
    { name: "Rufflet", claimed: false },
    { name: "Braviary", claimed: false },
    { name: "Vullaby", claimed: false },
    { name: "Mandibuzz", claimed: false },
    { name: "Heatmor", claimed: "MechanicalHippo" },
    { name: "Durant", claimed: "Serako" },
    { name: "Deino", claimed: "Jeakama" },
    { name: "Zweilous", claimed: "Darktrench" },
    { name: "Hydreigon", claimed: "Stevenchill" },
    { name: "Larvesta", claimed: "ANNlLlATION" },
    { name: "Volcarona", claimed: false }
  ]
};

// Helper function to create the image URL from the Pokémon name
function getPokemonGif(name) {
  if (name === "Mr. Mime") return "https://img.pokemondb.net/sprites/black-white/anim/shiny/mr-mime.gif";
  if (name === "Mime Jr.") return "https://img.pokemondb.net/sprites/black-white/anim/shiny/mime-jr.gif";
  if (name === "Nidoran♀") return "https://img.pokemondb.net/sprites/black-white/anim/shiny/nidoran-f.gif";
  if (name === "Nidoran♂") return "https://img.pokemondb.net/sprites/black-white/anim/shiny/nidoran-m.gif";

  let urlName = name
    .toLowerCase()
    .replace(/\u2640/g, "f")
    .replace(/\u2642/g, "m")
    .replace(/[\s.'’]/g, "");

  return `https://img.pokemondb.net/sprites/black-white/anim/shiny/${urlName}.gif`;
}

// Unified card renderer for Pokédex entries
function renderUnifiedCard(opts) {
  // opts: { name, img, info, lost }
  return `
    <div class="unified-card${opts.lost ? ' lost' : ''}">
      <div class="unified-name">${opts.name}</div>
      <img src="${opts.img}" alt="${opts.name}" class="unified-img"${opts.lost ? ' style="opacity:0.6;filter:grayscale(1);"' : ""}>
      <div class="unified-info${opts.lost ? ' lost' : ''}">${opts.info}</div>
    </div>
  `;
}

// Main rendering function for the shiny dex using unified cards
function renderShinyDex(regions) {
  const container = document.getElementById('shiny-dex-container');
  if (!container) return;
  container.innerHTML = '';
  Object.keys(regions).forEach(region => {
    const regionDiv = document.createElement('div');
    regionDiv.className = 'region-section';
    regionDiv.innerHTML = `<h2>${region}</h2>`;

    const grid = document.createElement('div');
    grid.className = 'dex-grid';

    regions[region].forEach(entry => {
      // Show only the member name if claimed, or empty if not
      let info = entry.claimed ? entry.claimed : "";
      grid.innerHTML += renderUnifiedCard({
        name: entry.name,
        img: getPokemonGif(entry.name),
        info
      });
    });
    regionDiv.appendChild(grid);
    container.appendChild(regionDiv);
  });
}
